/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "stm32f103C6_GPIO.h"
#include "stm32f103C6_EXTI.h"
#include "stm32f103C6_RCC.h"
#include "stm32f103C6_USART.h"
#include "stm32f103C6_SPI.h"
#include "keypad.h"
#include "lcd.h"
#include "I2C_E2PROM.h"

void Clock_Init(void){
	RCC_GPIOA_CLK_EN(); // GPIOA
	RCC_GPIOB_CLK_EN(); // GPIOB
	RCC_AFIO_CLK_EN();  // AFIO
}

int main(void)
{
	// Enable Clock
	Clock_Init();
	EEPROM_Init();

	//Test Case 1
	unsigned char ch1[7] = {0x1,0x2,0x3,0x4,0x5,0x6,0x7};
	unsigned char ch2[7] = {0};

	EEPROM_Write_Nbytes(0xAF, ch1, 7);
	EEPROM_Read_bytes(0xAF, ch2, 7);

	// Test Case 2
	ch1[0] = 0xA;
	ch1[1] = 0xB;
	ch1[2] = 0xC;
	ch1[3] = 0xD;

	EEPROM_Write_Nbytes(0xFFF, ch1, 4);
	EEPROM_Read_bytes(0xFFF, ch2, 4);


	// loop forever
	while(1){

	}

}

