/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stm32f103x6.h"
#include "stm32f103C6_GPIO.h"
#include "stm32f103C6_EXTI.h"
#include "keypad.h"
#include "lcd.h"

typedef volatile unsigned int vuint32_t;

uint8_t IRQ_Flag = 1;

void Clock_init(){
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

void GPIO_init(){

}

void EXTI9_CallBack(void){
	//EXTI9_5_IRQHandler();
	IRQ_Flag = 0;
	LCD_WRITE_STRING("IRQ9 interrupt has happened _|- ");
	wait(1000);
	LCD_clear_screen();
}

int main(void)
{
	// Enable Clock
	Clock_init();
	LCD_INIT();
	LCD_WRITE_STRING("hello");
	LCD_clear_screen();

	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RSISING;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enalbe;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_CallBack;

	MCAL_EXTI_GPIO_Init(&EXTI_CFG);



	while(1){
		if(IRQ_Flag){
		LCD_clear_screen();
		wait(100);
		}
		else{

		}
	}

}

