/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdio.h"
#include "stdlib.h"
#include "stdint.h"

typedef volatile unsigned int vuint32_t;


// register address
// GPIOA
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *) (GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *) (GPIOA_BASE + 0x0C)
#define GPIOA_CRL *(volatile uint32_t *) (GPIOA_BASE + 0x00)

// Clock
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)

// EXTI
#define EXTI_BASE 0x40010400
#define EXTI_IMR *(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR *(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR *(volatile uint32_t *)(EXTI_BASE + 0x14)

// NVIC
#define NVIC_EXTIE0 *(volatile uint32_t *)(0xE000E100)

// AFIO
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *(volatile uint32_t *)(AFIO_BASE + 0x14)

void clock_init(){
	// enable clock GPIOA
	// Enable IO port A clock
	// Bit 2 IOPAEN: IO port A clock enable
	// Set and cleared by software.
	// 0: IO port A clock disabled
	// 1: IO port A clock enabled
	RCC_APB2ENR |= (1<<2);

	/*Bit 0 AFIOEN: Alternate function IO clock enable
	Set and cleared by software.
	0: Alternate Function IO clock disabled
	1: Alternate Function IO clock enabled*/
	RCC_APB2ENR |= (1<<0);
}

void GPIO_init(){
	// inti GPIOA
	// pin 13 port A output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	// pinA0 input floating
	GPIOA_CRL |= (1<<2);
}

int main(void)
{
	clock_init();
	GPIO_init();
	// EXTI0 configuration to portA0
	AFIO_EXTICR1 = 0;
	// enable Rising trigger
	EXTI_RTSR |= (1<<0);
	// enable EXTI line 0
	EXTI_IMR |= (1<<0);
	// enable NVIC irq6 <<>> EXTI0
	NVIC_EXTIE0 |= (1<<6);
	while(1);

}

void EXTI0_IRQHandler(void){
	//IRQ has happened EXTI0 >>> PORTA pin 0 - rising edge
	//toggle led pin A 13
	GPIOA_ODR ^= (1<<13);

	//clear pending request for line 0
	EXTI_PR |= (1<<0);
}
