/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stm32f103x6.h"
#include "stm32f103C6_GPIO.h"
typedef volatile unsigned int vuint32_t;




void Clock_init(){
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

void GPIO_init(){
	GPIO_PinConfig_t PinCFG;
	// PA1--> floating input
	PinCFG.GPIO_PinNumber = GPIOx_PIN_1;
	PinCFG.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCFG);

	// PB1 --> output push pull
	PinCFG.GPIO_PinNumber = GPIOx_PIN_1;
	PinCFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_Output_Speed = GPIO_SPEED_10;
	MCAL_GPIO_Init(GPIOB, &PinCFG);

	// PA13 --> floating input
	PinCFG.GPIO_PinNumber = GPIOx_PIN_13;
	PinCFG.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCFG);

	// PB13 --> push pull output
	PinCFG.GPIO_PinNumber = GPIOx_PIN_13;
	PinCFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_Output_Speed = GPIO_SPEED_10;
	MCAL_GPIO_Init(GPIOB, &PinCFG);
}

void wait(uint32_t x){
	uint32_t i,j;
	for(i = 0; i <x; i++)
		for(j = 0; j < 255; j++);
}

int main(void)
{
    Clock_init();
    GPIO_init();
    while(1){
    	if(MCAL_GPIO_ReadPin(GPIOA, GPIOx_PIN_1) == 0){
    		MCAL_GPIO_TogglePin(GPIOB, GPIOx_PIN_1);
    		while(MCAL_GPIO_ReadPin(GPIOA, GPIOx_PIN_1) == 0);
    	}
    	if(MCAL_GPIO_ReadPin(GPIOA, GPIOx_PIN_13) == 1){
    		MCAL_GPIO_TogglePin(GPIOB, GPIOx_PIN_13);
    	}
    	wait(1);
    }
}

